# GitHub Actions workflow to build HTML site via Sphinx and deploy it
# to github.io via the gh-pages branch
#
# Primarily based on https://github.com/marketplace/actions/sphinx-docs-to-github-pages

name: Sphinx website to gh-pages

on:
  push:
    branches:
      - main

jobs:
  sphinx_website_to_gh-pages:
    name: Sphinx website to gh-pages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@422500192359a097648154e8db4e39bdb6c6eed7
        with:
           environment-file: envs/environment-gh-pages.yaml
           environment-name: numeric-gh-pages
           # persist downloads and environment caches for 1 day
           cache-downloads-key: downloads-${{ steps.date.outputs.date }}
           cache-environment-key: environment-${{ steps.date.outputs.date }}

      - name: Sphinx build and deploy
        uses: uibcdf/action-sphinx-docs-to-gh-pages@ae149a8d88b6b7ce5139a49112140048861a04c5
        with:
          branch: main
          dir_docs: website
          sphinx-apidoc: 'false'
          sphinx-opts: ''
